// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBO2snSERE5rbQRHRUASWc9O2upT5QNhDc',
    appId: '1:795620351781:web:c69f2a73ecd36542ccc4cc',
    messagingSenderId: '795620351781',
    projectId: 'flash-chat-2d103',
    authDomain: 'flash-chat-2d103.firebaseapp.com',
    storageBucket: 'flash-chat-2d103.appspot.com',
    measurementId: 'G-ZHMKSW9PBJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjYgK7b-rOhevr_G861Wo2_q_Xuatkv6A',
    appId: '1:795620351781:android:611aa10d895a6045ccc4cc',
    messagingSenderId: '795620351781',
    projectId: 'flash-chat-2d103',
    storageBucket: 'flash-chat-2d103.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADFFK3sMA4tUszCrofduLNcklmM_0pDZk',
    appId: '1:795620351781:ios:d6bbb403a98f62efccc4cc',
    messagingSenderId: '795620351781',
    projectId: 'flash-chat-2d103',
    storageBucket: 'flash-chat-2d103.appspot.com',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADFFK3sMA4tUszCrofduLNcklmM_0pDZk',
    appId: '1:795620351781:ios:eb0401caec92b935ccc4cc',
    messagingSenderId: '795620351781',
    projectId: 'flash-chat-2d103',
    storageBucket: 'flash-chat-2d103.appspot.com',
    iosBundleId: 'com.example.flashChat.RunnerTests',
  );
}
